//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Importador_de_Etiquetas.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EtiquetasEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EtiquetasEntities usando la cadena de conexión encontrada en la sección 'EtiquetasEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public EtiquetasEntities() : base("name=EtiquetasEntities", "EtiquetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EtiquetasEntities.
        /// </summary>
        public EtiquetasEntities(string connectionString) : base(connectionString, "EtiquetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EtiquetasEntities.
        /// </summary>
        public EtiquetasEntities(EntityConnection connection) : base(connection, "EtiquetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<catalog_comandos_etiquetas> catalog_comandos_etiquetas
        {
            get
            {
                if ((_catalog_comandos_etiquetas == null))
                {
                    _catalog_comandos_etiquetas = base.CreateObjectSet<catalog_comandos_etiquetas>("catalog_comandos_etiquetas");
                }
                return _catalog_comandos_etiquetas;
            }
        }
        private ObjectSet<catalog_comandos_etiquetas> _catalog_comandos_etiquetas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet catalog_comandos_etiquetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocatalog_comandos_etiquetas(catalog_comandos_etiquetas catalog_comandos_etiquetas)
        {
            base.AddObject("catalog_comandos_etiquetas", catalog_comandos_etiquetas);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EtiquetasModel", Name="catalog_comandos_etiquetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class catalog_comandos_etiquetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto catalog_comandos_etiquetas.
        /// </summary>
        /// <param name="id_comando">Valor inicial de la propiedad id_comando.</param>
        /// <param name="etiqueta">Valor inicial de la propiedad etiqueta.</param>
        /// <param name="comando">Valor inicial de la propiedad comando.</param>
        /// <param name="imagen_etiqueta">Valor inicial de la propiedad imagen_etiqueta.</param>
        public static catalog_comandos_etiquetas Createcatalog_comandos_etiquetas(global::System.Int32 id_comando, global::System.String etiqueta, global::System.String comando, global::System.Byte[] imagen_etiqueta)
        {
            catalog_comandos_etiquetas catalog_comandos_etiquetas = new catalog_comandos_etiquetas();
            catalog_comandos_etiquetas.id_comando = id_comando;
            catalog_comandos_etiquetas.etiqueta = etiqueta;
            catalog_comandos_etiquetas.comando = comando;
            catalog_comandos_etiquetas.imagen_etiqueta = imagen_etiqueta;
            return catalog_comandos_etiquetas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comando
        {
            get
            {
                return _id_comando;
            }
            set
            {
                if (_id_comando != value)
                {
                    Onid_comandoChanging(value);
                    ReportPropertyChanging("id_comando");
                    _id_comando = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_comando");
                    Onid_comandoChanged();
                }
            }
        }
        private global::System.Int32 _id_comando;
        partial void Onid_comandoChanging(global::System.Int32 value);
        partial void Onid_comandoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String etiqueta
        {
            get
            {
                return _etiqueta;
            }
            set
            {
                OnetiquetaChanging(value);
                ReportPropertyChanging("etiqueta");
                _etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("etiqueta");
                OnetiquetaChanged();
            }
        }
        private global::System.String _etiqueta;
        partial void OnetiquetaChanging(global::System.String value);
        partial void OnetiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comando
        {
            get
            {
                return _comando;
            }
            set
            {
                OncomandoChanging(value);
                ReportPropertyChanging("comando");
                _comando = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comando");
                OncomandoChanged();
            }
        }
        private global::System.String _comando;
        partial void OncomandoChanging(global::System.String value);
        partial void OncomandoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] imagen_etiqueta
        {
            get
            {
                return StructuralObject.GetValidValue(_imagen_etiqueta);
            }
            set
            {
                Onimagen_etiquetaChanging(value);
                ReportPropertyChanging("imagen_etiqueta");
                _imagen_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imagen_etiqueta");
                Onimagen_etiquetaChanged();
            }
        }
        private global::System.Byte[] _imagen_etiqueta;
        partial void Onimagen_etiquetaChanging(global::System.Byte[] value);
        partial void Onimagen_etiquetaChanged();

        #endregion

    
    }

    #endregion

    
}
